export interface Voice {
  id: string;
  name: string;
  email: string;
  languages: string;
  styles: string;
  pricePerHour: number;
  audioSamplePath: string;
  description: string;
  gender: string;
  age: number;
  avatarUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export const voices: Voice[] = [
  {
    id: 'sarah-mitchell',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@voicehub.com',
    languages: JSON.stringify(['English', 'French']),
    styles: JSON.stringify(['Commercial', 'E-Learning']),
    pricePerHour: 15000,
    audioSamplePath: '/audio/samples/sarah-mitchell.mp3',
    description: 'Warm and engaging voice with over 10 years of experience in commercial and educational content. Known for clear articulation and friendly tone that connects with audiences.',
    gender: 'female',
    age: 32,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'marcus-chen',
    name: 'Marcus Chen',
    email: 'marcus.chen@voicehub.com',
    languages: JSON.stringify(['English', 'Mandarin']),
    styles: JSON.stringify(['Narration', 'Documentary']),
    pricePerHour: 18000,
    audioSamplePath: '/audio/samples/marcus-chen.mp3',
    description: 'Deep, authoritative voice perfect for documentaries and narration. Bilingual in English and Mandarin with experience in international productions.',
    gender: 'male',
    age: 45,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'elena-rodriguez',
    name: 'Elena Rodriguez',
    email: 'elena.rodriguez@voicehub.com',
    languages: JSON.stringify(['English', 'Spanish', 'Portuguese']),
    styles: JSON.stringify(['Commercial', 'Animation']),
    pricePerHour: 12000,
    audioSamplePath: '/audio/samples/elena-rodriguez.mp3',
    description: 'Versatile trilingual voice artist specializing in character work and commercials. Brings energy and authenticity to every project.',
    gender: 'female',
    age: 28,
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'james-williams',
    name: 'James Williams',
    email: 'james.williams@voicehub.com',
    languages: JSON.stringify(['English']),
    styles: JSON.stringify(['Audiobook', 'Podcast']),
    pricePerHour: 20000,
    audioSamplePath: '/audio/samples/james-williams.mp3',
    description: 'Award-winning audiobook narrator with a rich, captivating voice. Specializes in fiction and long-form content with excellent pacing.',
    gender: 'male',
    age: 52,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    id: 'yuki-tanaka',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@voicehub.com',
    languages: JSON.stringify(['English', 'Japanese']),
    styles: JSON.stringify(['Animation', 'E-Learning']),
    pricePerHour: 14000,
    audioSamplePath: '/audio/samples/yuki-tanaka.mp3',
    description: 'Bright, expressive voice ideal for animation and educational content. Native Japanese speaker with perfect American English.',
    gender: 'female',
    age: 26,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'david-muller',
    name: 'David Müller',
    email: 'david.muller@voicehub.com',
    languages: JSON.stringify(['English', 'German']),
    styles: JSON.stringify(['Commercial', 'Documentary']),
    pricePerHour: 16000,
    audioSamplePath: '/audio/samples/david-muller.mp3',
    description: 'Professional bilingual voice with a sophisticated European sound. Extensive experience in corporate and documentary projects.',
    gender: 'male',
    age: 38,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    id: 'sofia-laurent',
    name: 'Sofia Laurent',
    email: 'sofia.laurent@voicehub.com',
    languages: JSON.stringify(['French', 'English']),
    styles: JSON.stringify(['Narration', 'Audiobook']),
    pricePerHour: 17500,
    audioSamplePath: '/audio/samples/sofia-laurent.mp3',
    description: 'Elegant French voice with impeccable English. Specializes in literary narration and luxury brand content.',
    gender: 'female',
    age: 35,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'alex-kim',
    name: 'Alex Kim',
    email: 'alex.kim@voicehub.com',
    languages: JSON.stringify(['English', 'Korean']),
    styles: JSON.stringify(['Podcast', 'Commercial']),
    pricePerHour: 13000,
    audioSamplePath: '/audio/samples/alex-kim.mp3',
    description: 'Fresh, modern voice perfect for podcasts and digital content. Brings authenticity and relatability to every read.',
    gender: 'non-binary',
    age: 24,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'isabella-rossi',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@voicehub.com',
    languages: JSON.stringify(['English', 'Italian']),
    styles: JSON.stringify(['Commercial', 'Animation']),
    pricePerHour: 14500,
    audioSamplePath: '/audio/samples/isabella-rossi.mp3',
    description: 'Passionate and expressive voice with Italian flair. Excellent for character work and emotive commercial content.',
    gender: 'female',
    age: 30,
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: 'thomas-anderson',
    name: 'Thomas Anderson',
    email: 'thomas.anderson@voicehub.com',
    languages: JSON.stringify(['English']),
    styles: JSON.stringify(['Documentary', 'E-Learning']),
    pricePerHour: 15500,
    audioSamplePath: '/audio/samples/thomas-anderson.mp3',
    description: 'Clear, trustworthy voice ideal for educational and documentary content. Known for making complex topics accessible.',
    gender: 'male',
    age: 41,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'marie-dubois',
    name: 'Marie Dubois',
    email: 'marie.dubois@voicehub.com',
    languages: JSON.stringify(['French', 'English']),
    styles: JSON.stringify(['Audiobook', 'Narration']),
    pricePerHour: 18500,
    audioSamplePath: '/audio/samples/marie-dubois.mp3',
    description: 'Sophisticated voice with a gentle French accent. Premier choice for literary audiobooks and premium narration.',
    gender: 'female',
    age: 48,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: 'chris-johnson',
    name: 'Chris Johnson',
    email: 'chris.johnson@voicehub.com',
    languages: JSON.stringify(['English']),
    styles: JSON.stringify(['Podcast', 'Commercial']),
    pricePerHour: 11000,
    audioSamplePath: '/audio/samples/chris-johnson.mp3',
    description: 'Friendly, conversational voice perfect for podcasts and casual commercial content. Great at connecting with younger audiences.',
    gender: 'male',
    age: 29,
    avatarUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&h=200&fit=crop&crop=face',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
];
